USE KONNECT;

CREATE TABLE IF NOT EXISTS USERS (
  EMAIL VARCHAR(50),
  USERNAME VARCHAR(255),
  PASSWD VARCHAR(255),
  ADDRESS VARCHAR(255),
  PROFILE_PIC_PATH VARCHAR(100),
  CONTACT_NO CHAR(10),
  PRIMARY KEY(EMAIL)
);

CREATE TABLE IF NOT EXISTS POSTS (
  POST_ID INT AUTO_INCREMENT,
  OWNER VARCHAR(50),
  TITLE VARCHAR(255),
  BODY MEDIUMTEXT,
  PRICE INT NOT NULL,
  IMAGE_PATHS MEDIUMTEXT,

  PRIMARY KEY(POST_ID),
  FOREIGN KEY(OWNER) REFERENCES USERS(EMAIL)
);

