CREATE TABLE IF NOT EXISTS USERS (
  EMAIL VARCHAR(50),
  USERNAME VARCHAR(255) NOT NULL,
  PASSWD VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  PROFILE_PIC_PATH VARCHAR(100),
  OPEN_TIMESTAMP timestamp default (timezone('utc', now())) not null,
  CONTACT_NO CHAR(10) NOT NULL,

  PRIMARY KEY(EMAIL)
);

CREATE TABLE IF NOT EXISTS POSTS (
  POST_ID INT generated always as identity,
  OWNER VARCHAR(50) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  BODY TEXT,
  OPEN_TIMESTAMP timestamp default (timezone('utc', now())) not null,
  PRICE INT NOT NULL,
  IMAGE_PATHS TEXT[],

  PRIMARY KEY(POST_ID),
  FOREIGN KEY(OWNER) REFERENCES USERS(EMAIL)
);

